/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adventureworks2019;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vfern
 */
public class SalesOrderHeader extends javax.swing.JFrame {

    /**
     * Creates new form SalesOrderHeader
     */
    tamano t = new tamano();

    public SalesOrderHeader() {
        this.setLocation(t.Ancho() / 6, t.altura() / 20);
        initComponents();
        Ver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        TSOH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SOID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        S = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        OOF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SON = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PON = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SPID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BTAID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SMID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CCID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CCAC = new javax.swing.JTextField();
        STAID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CRID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AN = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ST = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TA = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        F = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        OD = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        DD = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        SD = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        R = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        MD = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JToggleButton();
        Modificar = new javax.swing.JToggleButton();
        Guardar = new javax.swing.JToggleButton();
        Nuevo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Cus = new javax.swing.JMenuItem();
        sod = new javax.swing.JMenuItem();
        sop = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sesion = new javax.swing.JMenuItem();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SalesOrderHeader");

        TSOH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SalesOrderID", "RevisionNumber", "OrderDate", "DueDate", "ShipDate", "Status", "OnlineOrderFlag", "SalesOrderNumber", "PurchaseOrderNumber", "AccountNumber", "CustomerID", "SalesPersonID", "TerritoryID", "BillToAddressID", "ShipToAddessID", "ShipMethodID", "CreditCardID", "CreditCardApprovalCode", "CurrencyRateID", "SubTotal", "TaxAmt", "Freight", "TotalDue", "Comment", "Rowguid", "ModifiedDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Short.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TSOH.setAutoResizeMode(0);
        TSOH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TSOHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TSOH);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setText("Datos");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("Sales Order Header");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("SalesOrderID");

        SOID.setEditable(false);

        jLabel4.setText("RevisionNumber");

        jLabel5.setText("Status");

        jLabel6.setText("OnlineOrderFlag");

        jLabel7.setText("SalesOrderNumber");

        SON.setEnabled(false);

        jLabel8.setText("PurchaseOrderNumber");

        jLabel10.setText("CustomerID");

        jLabel11.setText("SalesPersonID");

        SPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPIDActionPerformed(evt);
            }
        });

        jLabel12.setText("TerritoryID");

        jLabel13.setText("BillToAddressID");

        jLabel14.setText("ShipToAddressID");

        jLabel15.setText("ShipMethodID");

        jLabel16.setText("CreditCardID");

        jLabel17.setText("CreditCardApprovalCode");

        STAID.setEnabled(false);

        jLabel18.setText("CurrencyRateID");

        jLabel9.setText("AccountNumber");

        AN.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SPID, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(STAID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SMID)
                            .addComponent(BTAID)
                            .addComponent(TID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CRID)
                            .addComponent(CCAC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CCID, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SON, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(OOF)
                            .addComponent(S)
                            .addComponent(RN)
                            .addComponent(SOID)
                            .addComponent(PON)
                            .addComponent(AN))))
                .addGap(4, 4, 4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(OOF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(SPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(BTAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(STAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(SMID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CCAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(CRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel19.setText("SubTotal");

        jLabel20.setText("TaxAmt");

        jLabel21.setText("Freight");

        jLabel22.setText("TotalDue");

        TD.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TA, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(ST, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TD))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("OrderDate");

        OD.setEnabled(false);

        jLabel24.setText("DueDate");

        DD.setEnabled(false);

        jLabel25.setText("ShipDate");

        SD.setEnabled(false);

        jLabel26.setText("Rowguid");

        R.setEnabled(false);

        jLabel27.setText("ModifiedDate");

        MD.setEnabled(false);

        jLabel28.setText("Comment");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MD)
                    .addComponent(OD)
                    .addComponent(DD)
                    .addComponent(SD)
                    .addComponent(R)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(C))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Delete.setText("Eliminar");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Clear.setText("Limpiar");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        jMenu1.setText("Tabla");

        Cus.setText("Customer");
        Cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusActionPerformed(evt);
            }
        });
        jMenu1.add(Cus);

        sod.setText("SalesOrderDetail");
        sod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sodActionPerformed(evt);
            }
        });
        jMenu1.add(sod);

        sop.setText("SpecialOfferProduct");
        sop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sopActionPerformed(evt);
            }
        });
        jMenu1.add(sop);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Sesión");

        sesion.setText("Cerrar");
        sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionActionPerformed(evt);
            }
        });
        jMenu3.add(sesion);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear)
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Delete)
                                .addComponent(Clear)
                                .addComponent(Modificar)
                                .addComponent(Guardar)
                                .addComponent(Nuevo)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TSOHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TSOHMouseClicked
        // TODO add your handling code here:

        int selec = TSOH.rowAtPoint(evt.getPoint());
        int fila = TSOH.getSelectedRow();
        int ID = Integer.parseInt(TSOH.getValueAt(fila, 0).toString());

        try {
            Connection con = Conector.getConexion();
            PreparedStatement ps;
            ResultSet rs;
            String consulta = "SELECT * FROM Sales.SalesOrderHeader WHERE SalesOrderID = ?";
            ps = con.prepareStatement(consulta);
            ps.setInt(1, ID);
            rs = ps.executeQuery();

            while (rs.next()) {
                //SOID.setText(String.valueOf(SalesOrderID));

                SOID.setText(TSOH.getValueAt(selec, 0) + "");
                RN.setText(TSOH.getValueAt(selec, 1) + "");
                OD.setText(TSOH.getValueAt(selec, 2) + "");
                DD.setText(TSOH.getValueAt(selec, 3) + "");
                SD.setText(TSOH.getValueAt(selec, 4) + "");
                S.setText(TSOH.getValueAt(selec, 5) + "");
                OOF.setText(TSOH.getValueAt(selec, 6) + "");
                SON.setText(TSOH.getValueAt(selec, 7) + "");
                PON.setText(TSOH.getValueAt(selec, 8) + "");
                AN.setText(TSOH.getValueAt(selec, 9) + "");
                CID.setText(TSOH.getValueAt(selec, 10) + "");
                SPID.setText(TSOH.getValueAt(selec, 11) + "");
                TID.setText(TSOH.getValueAt(selec, 12) + "");

                BTAID.setText(TSOH.getValueAt(selec, 13) + "");
                STAID.setText(TSOH.getValueAt(selec, 14) + "");
                SMID.setText(TSOH.getValueAt(selec, 15) + "");
                CCID.setText(TSOH.getValueAt(selec, 16) + "");
                CCAC.setText(TSOH.getValueAt(selec, 17) + "");
                CRID.setText(TSOH.getValueAt(selec, 18) + "");
                ST.setText(TSOH.getValueAt(selec, 19) + "");
                TA.setText(TSOH.getValueAt(selec, 20) + "");
                F.setText(TSOH.getValueAt(selec, 21) + "");
                TD.setText(TSOH.getValueAt(selec, 22) + "");
                C.setText(TSOH.getValueAt(selec, 23) + "");
                R.setText(TSOH.getValueAt(selec, 24) + "");
                MD.setText(TSOH.getValueAt(selec, 25) + "");

            }

        } catch (SQLException e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(null, "Error X_x");

        }

    }//GEN-LAST:event_TSOHMouseClicked

    private void SPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPIDActionPerformed

    private void CusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusActionPerformed
        // TODO add your handling code here:
        Customer c = new Customer();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CusActionPerformed

    private void sodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sodActionPerformed
        // TODO add your handling code here:
        SalesOrderDetail sod = new SalesOrderDetail();
        sod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sodActionPerformed

    private void sopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sopActionPerformed
        // TODO add your handling code here:
        SpecialOfferProduct sop = new SpecialOfferProduct();
        sop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sopActionPerformed

    private void sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Hasta Luego UuU");
        Menu M = new Menu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sesionActionPerformed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(SOID.getText());
            Connection con = Conector.getConexion();
            String consulta = "DELETE FROM Sales.SalesOrderHeader where SalesOrderID = ? ";
            PreparedStatement ps = con.prepareStatement(consulta);
            ps.setInt(1, id);
            ps.executeUpdate();
            ps.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            Ver();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_ClearMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:

        Timestamp Time = new Timestamp(System.currentTimeMillis());

        int SalesOrderID = Integer.parseInt(SOID.getText());
        short RevisionNumber = Short.valueOf(RN.getText());
        short Status = Short.valueOf(S.getText());
        boolean OnlineOrderFlag = Boolean.parseBoolean(OOF.getText());

        String PurchaseOrderNumber = "";
        PurchaseOrderNumber = AUXS(PON.getText());

        int CustomerID = Integer.parseInt(CID.getText());

        String AccountNumber = "";
        String ax = String.valueOf(CustomerID);
        String ax2 = "10-4030-0";
        ax2 = ax2.concat(ax); 
        AN.setText(ax2);
        AccountNumber = AN.getText();

        Integer spid = 0;
        spid = AUXI(SPID.getText());

        int TerritoryID = Integer.parseInt(TID.getText());
        int BillToAddressID = Integer.parseInt(BTAID.getText());
        int ShipToAddressID = BillToAddressID;
        int ShipMethodID = Integer.parseInt(SMID.getText());
        int CreaditCardID = Integer.parseInt(CCID.getText());
        String CreaditCardApprovalCode = CCAC.getText();

        Integer CurrencyRateID = 0;
        CurrencyRateID = AUXI(CRID.getText());

        double SubTotal = Double.valueOf(ST.getText());
        double TaxAmt = Double.valueOf(TA.getText());
        double Freight = Double.valueOf(F.getText());
        String Comment = "";
        Comment = AUXS(C.getText());

        String rowguid = R.getText();

        /*

         */
        try {
            //Class.forName(driver);
            Connection con = Conector.getConexion();
            String consulta = "set Identity_insert Sales.SalesOrderHeader ON "
                    + "insert into Sales.SalesOrderHeader(SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,"
                    //                                          1         2                3      4       5
                    + "\"Status\",OnlineOrderFlag,PurchaseOrderNumber,AccountNumber,CustomerID,"
                    //      6         7                8                    9            10
                    + "SalesPersonID,TerritoryID,BillToAddressID,"
                    //      11          12              13
                    + "ShipToAddressID,ShipMethodID,"
                    //           14           15
                    + "CreditCardID,CreditCardApprovalCode,CurrencyRateID,"
                    //       16           17                       18
                    + "SubTotal,TaxAmt,Freight,Comment,rowguid,ModifiedDate) "
                    //    19      20      21      22      23      24
                    + "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)  "
                    + "set Identity_insert Sales.SalesOrderHeader OFF";

            PreparedStatement ps = con.prepareStatement(consulta);


            // ps.setInt(1, SalesOrderID);
            /*1*/ ps.setInt(1, SalesOrderID);
            /*2*/ ps.setInt(2, RevisionNumber);
            /*3*/ ps.setTimestamp(3, Time);
            /*4*/ ps.setTimestamp(4, Time);
            /*5*/ ps.setTimestamp(5, Time);
            /*6*/ ps.setShort(6, Status);
            /*7*/ ps.setBoolean(7, OnlineOrderFlag);
            /*8*/ ps.setString(8, PurchaseOrderNumber);
            /*9*/ ps.setString(9, AccountNumber);
            /*10*/ ps.setInt(10, CustomerID);
            /*11*/
            ps.setInt(11, spid);
            /*12*/
            ps.setInt(12, TerritoryID);
            /*13*/
            ps.setInt(13, BillToAddressID);
            /*14*/
            ps.setInt(14, ShipToAddressID);
            /*15*/
            ps.setInt(15, ShipMethodID);
            /*16*/
            ps.setInt(16, CreaditCardID);
            /*17*/
            ps.setString(17, CreaditCardApprovalCode);
            /*18*/
            ps.setInt(18, CurrencyRateID);
            /*19*/
            ps.setDouble(19, SubTotal);
            /*20*/
            ps.setDouble(20, TaxAmt);
            /*21*/
            ps.setDouble(21, Freight);
            //  ps.setDouble(22, TotalDue);
            ps.setString(22, Comment);
            ps.setString(23, rowguid);
            ps.setTimestamp(24, Time);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Guardado UwU");
            ps.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
            //System.out.println(e.toString());
        }


    }//GEN-LAST:event_GuardarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
        Limpiar();
        Timestamp Time = new Timestamp(System.currentTimeMillis());
        SOID.setText(String.valueOf(SOID_U()));
        SON.setText(String.valueOf(SON_U()));
        OD.setText(String.valueOf(Time));
        DD.setText(String.valueOf(Time));
        SD.setText(String.valueOf(Time));
        String h = "79B65321-39CA-4115-9CBA-8FE" + SOID.getText() + "12E7A";
        R.setText(h);
        MD.setText(String.valueOf(Time));

    }//GEN-LAST:event_NuevoActionPerformed

    private String AUXS(String h) {
        int a = h.length();
        if (a == 0) {
            h = null;
        }
        return h;
    }

    private Integer AUXI(String l) {
        int aux = l.length();
        Integer a;
        if (aux == 0) {
            return null;
        }
        a = Integer.parseInt(l);
        return a;

    }

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        /*1 */ int SalesOrderID = Integer.parseInt(SOID.getText());
        /*2 */ short RevisionNumber = Short.valueOf(RN.getText());
        /*3 */ Timestamp OrderDate = Timestamp.valueOf(OD.getText());
        /*4 */ Timestamp DueDate = Timestamp.valueOf(DD.getText());
        /*5 */ Timestamp ShipDate = Timestamp.valueOf(SD.getText());
        /*6 */ short Status = Short.valueOf(S.getText());
        /*7 */ boolean OnlineOrderFlag = Boolean.parseBoolean(OOF.getText());

        /*8 */ String PurchaseOrderNumber = PON.getText();

        /*9 */ int CustomerID = Integer.parseInt(CID.getText());
        /*10 */ String AccountNumber = "10-4030-0";
        String aux = String.valueOf(CustomerID);
        AccountNumber = AccountNumber.concat(aux);

        /*11 */ int SalesPersonID = Integer.parseInt(SPID.getText());
        /*12*/ int TerritoryID = Integer.parseInt(TID.getText());
        /*13*/ int BillToAddressID = Integer.parseInt(BTAID.getText());
        STAID.setText(BTAID.getText());
        /*14*/ int ShipToAddressID = Integer.parseInt(STAID.getText());
        /*15*/ int ShipMethodID = Integer.parseInt(SMID.getText());
        /*16*/ int CreaditCardID = Integer.parseInt(CCID.getText());
        /*17*/ String CreaditCardApprovalCode = CCAC.getText();
        /*18*/ int CurrencyRateID = Integer.parseInt(CRID.getText());
        /*19*/ double SubTotal = Float.parseFloat(ST.getText());
        /*20*/ double TaxAmt = Float.parseFloat(TA.getText());
        /*21*/ double Freight = Float.parseFloat(F.getText());
        /*22*/ String Comment = C.getText();
        /*23*/ String rowguid = R.getText();
        /*24*/ Timestamp ModifiedDate = Timestamp.valueOf(MD.getText());

        try {
            Connection con = Conector.getConexion();
            String consulta = "UPDATE Sales.SalesOrderHeader SET "
                    + "RevisionNumber=?,Status=?,OnlineOrderFlag=?,PurchaseOrderNumber=?,AccountNumber=?,CustomerID=?,"
                    //           1          2         3                   4                    5            6
                    + "SalesPersonID=?,TerritoryID=?,BillToAddressID=?,"
                    //      7               8              9
                    + "ShipToAddressID=?,ShipMethodID=?,"
                    //           10           11
                    + "CreditCardID=?,CreditCardApprovalCode=?,CurrencyRateID=?,"
                    //       12               13                      14
                    + "SubTotal=?,TaxAmt=?,Freight=?,Comment=? where SalesOrderID=?";
            //       15        16      17         18   

            PreparedStatement ps = con.prepareStatement(consulta);

            ps.setShort(1, RevisionNumber);
            ps.setShort(2, Status);
            ps.setBoolean(3, OnlineOrderFlag);
            ps.setString(4, PurchaseOrderNumber);
            ps.setString(5, AccountNumber);
            ps.setInt(6, CustomerID);
            ps.setInt(7, SalesPersonID);
            ps.setInt(8, TerritoryID);
            ps.setInt(9, BillToAddressID);
            ps.setInt(10, ShipToAddressID);
            ps.setInt(11, ShipMethodID);
            ps.setInt(12, CreaditCardID);
            ps.setString(13, CreaditCardApprovalCode);
            ps.setInt(14, CurrencyRateID);
            ps.setDouble(15, SubTotal);
            ps.setDouble(16, TaxAmt);
            ps.setDouble(17, Freight);
            ps.setString(18, Comment);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Modificado UwU");

        } catch (SQLException e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Ver() {
        DefaultTableModel T = (DefaultTableModel) TSOH.getModel();
        T.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columna;
        int[] anchos = {80, 70, 160, 160, 160, 60, 110, 120, 150, 120, 80, 80, 80, 80, 80, 80, 80, 100, 50, 80, 80, 80, 80, 80, 280, 160};
        for (int i = 0; i < TSOH.getColumnCount(); i++) {
            TSOH.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }

        try {
            Connection con = Conector.getConexion();
            String consulta = "SELECT * FROM sales.SalesOrderHeader";
            ps = con.prepareStatement(consulta);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columna = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columna];
                for (int i = 0; i < columna; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                T.addRow(fila);
            }

        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    public void Limpiar() {
        SOID.setText("");
        RN.setText("");
        OD.setText("");
        DD.setText("");
        SD.setText("");
        S.setText("");
        OOF.setText("");
        SON.setText("");
        PON.setText("");
        AN.setText("");
        CID.setText("");
        SPID.setText("");
        TID.setText("");

        BTAID.setText("");
        STAID.setText("");
        SMID.setText("");
        CCID.setText("");
        CCAC.setText("");
        CRID.setText("");
        ST.setText("");
        TA.setText("");
        F.setText("");
        TD.setText("");
        C.setText("");
        R.setText("");
        MD.setText("");
    }

    private int SOID_U() {
        int u = 0;
        PreparedStatement ps;
        ResultSet rs;

        try {
            Connection con = Conector.getConexion();
            String consulta = "SELECT top 1 SalesOrderID  FROM Sales.SalesOrderHeader order by SalesOrderID desc";
            ps = con.prepareStatement(consulta);
            rs = ps.executeQuery();
            while (rs.next()) {
                u = Integer.parseInt(rs.getString("SalesOrderID"));
            }
            u++;
            return u;
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
        return -1;
    }

    private String SON_U() {
        String son = "SO";
        String aux = String.valueOf(SOID_U());

        son = son.concat(aux);
        return son;

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesOrderHeader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesOrderHeader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesOrderHeader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesOrderHeader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesOrderHeader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AN;
    private javax.swing.JTextField BTAID;
    private javax.swing.JTextField C;
    private javax.swing.JTextField CCAC;
    private javax.swing.JTextField CCID;
    private javax.swing.JTextField CID;
    private javax.swing.JTextField CRID;
    private javax.swing.JToggleButton Clear;
    private javax.swing.JMenuItem Cus;
    private javax.swing.JTextField DD;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField F;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JTextField MD;
    private javax.swing.JToggleButton Modificar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField OD;
    private javax.swing.JTextField OOF;
    private javax.swing.JTextField PON;
    private javax.swing.JTextField R;
    private javax.swing.JTextField RN;
    private javax.swing.JTextField S;
    private javax.swing.JTextField SD;
    private javax.swing.JTextField SMID;
    private javax.swing.JTextField SOID;
    private javax.swing.JTextField SON;
    private javax.swing.JTextField SPID;
    private javax.swing.JTextField ST;
    private javax.swing.JTextField STAID;
    private javax.swing.JTextField TA;
    private javax.swing.JTextField TD;
    private javax.swing.JTextField TID;
    private javax.swing.JTable TSOH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem sesion;
    private javax.swing.JMenuItem sod;
    private javax.swing.JMenuItem sop;
    // End of variables declaration//GEN-END:variables
}
